### ISSUE TITLE
resource does not exist warning

### ISSUE THREAD

**Issue by julianrichie** [mike-goodwin/connect-azuretables#1] opened 2016-04-13 16:41 UTC
i'm receiving this resource does not exist warning when working on my local, everything went fine if i uploaded the code to ms azure host
![screen shot 2016-04-13 at 3 36 54 pm](https://cloud.githubusercontent.com/assets/1916616/14501443/bf401932-01d0-11e6-986a-bb30fe796b20.png)

**Comment by mike-goodwin** [comment] 2016-04-13 22:00
Please can you tell me at what point does the error occur? Is it saving a session, reading one or destroying one? I think I saw this at one point where it seemed like Passport was attempting to read the session before the create was complete. Is this what is happening for you?

**Comment by julianrichie** [comment] 2016-04-14 02:27
I guessing theres some overlapping function between session saving and get/send everytime an oauth callback is called and redirect to successfull login pages

**Comment by mike-goodwin** [comment] 2016-04-14 07:55
It sounds that way. I was able to reproduce your error by modifying my demo app a bit and it looks like the session "get" is happening immediately after it is initially created and before the callback from the "save" is triggered. It could explain why it is working when on Azure because the latency of the table storage request would be very low when calling from Azure compared to calling from your local machine. I have three thoughts on how to fix this:

1. Allow retries on 404 status codes from the table storage client. Currently it uses a standard retry policy from the Azure SDK for nodejs that does not retry on 404s - maybe the neatest solution but complex to implement
2. Just manually put some retry logic into the session get function - very simple to implement but feels a bit hacky
3. Cache the session data in memory for the duration of the save and the have the get fetch it from cache if it is called before the save callback happens - not sure if this would work in a load-balanced environment though

I'm at work now, but I'll mull it over and try to implement later. Of course, if you feel like making a PR to fix it that would be great too :o)

**Comment by julianrichie** [comment] 2016-04-14 16:01
I forgot to mention about the "other effect" for this warning is req.isAuthenticated() always return true although req.logout /logout path is called, i have to clear all the cookies/history to get clean again

**Comment by mike-goodwin** [comment] 2016-04-14 19:37
OK, I added some retry logic to the session get to handle the race condition where the set is slow to call back and a unit test for it. I also updated the demo app. I am no longer able to reproduce the error so I think this is fixed, although I think it could still happen if the set was VERY slow. The fix is in NPM package v1.0.14. Would you be able to give it a try to see if you still get the issue? I'll leave this open until I hear back from you...

**Comment by julianrichie** [comment] 2016-04-15 05:59
Ok, thx i'll give it a try

**Comment by mike-goodwin** [comment] 2016-04-19 12:23
Hello @julianrichie. How is this working for you? Has it resolved your problem?

**Comment by julianrichie** [comment] 2016-04-19 13:11
i've been testing (locally) for the last 2 days, and it seems to be working, no error was found for the last 2 days 👍 👍

**Comment by mike-goodwin** [comment] 2016-04-19 14:51
OK, great. I'll close this issue then. Feel free to reopen if it reappears.

**Closed by mike-goodwin** 2016-04-19 14:51 UTC

**Comment by mike-goodwin** [comment] 2016-07-06 10:13
This turns out to be an issue with Passport. The hacky fix that I put in will continue to work, but in case you ever change session stores, you might want to use the workaround described here:

https://github.com/expressjs/session/issues/309#issuecomment-230594298
