### ISSUE TITLE
"The specified resource does not exist" error on session.destroy()

### ISSUE THREAD

**Issue by ailon** [mike-goodwin/connect-azuretables#4] opened 2017-03-30 11:04 UTC
Thank you for a great package! However, every time I call `req.session.destroy()` the whole app is brought down by the subject error and it doesn't get fixed until you clear cookies from the browser manually.

Additionally, this gets me worried that the same issue might happen when sessions are auto-deleted from the store periodically while session cookie is still present in the client browser.

Am I doing something wrong?

Here's the error and stack trace:

```
The specified resource does not exist. RequestId:454dd22d-0002-0096-5b43-a9a387000000 Time:2017-03-30T10:47:51.8208871Z

StorageError: The specified resource does not exist.
RequestId:454dd22d-0002-0096-5b43-a9a387000000
Time:2017-03-30T10:47:51.8208871Z
    at Function.StorageServiceClient._normalizeError ([local-path]\node_modules\connect-azuretables\node_modules\azure-storage\lib\common\services\storageserviceclient.js:1174:23)
    at Object.StorageServiceClient._processResponse ([local-path]\node_modules\connect-azuretables\node_modules\azure-storage\lib\common\services\storageserviceclient.js:729:50)
    at Request.processResponseCallback [as _callback] ([local-path]\node_modules\connect-azuretables\node_modules\azure-storage\lib\common\services\storageserviceclient.js:310:37)
    at Request.init.self.callback ([local-path]\node_modules\connect-azuretables\node_modules\request\request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> ([local-path]\node_modules\connect-azuretables\node_modules\request\request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> ([local-path]\node_modules\connect-azuretables\node_modules\request\request.js:965:12)
```

**Comment by mike-goodwin-sage** [comment] 2017-03-30 12:29
Hello,

I' afraid I can't reproduce this - it works find in my sample app, my real app and my tests. If you are able to post some code I will be happy to look into it. In the meantime, a couple of thoughts:

- Are you using the most up to date package (1.0.17)?
- Are you sure the session info is being successfully written to the store?
- Could it be that the session is expiring and being deleted in the background before you call `destroy()`? If so then the library will just call the callback you supply to `session.destroy()` - it does not attempt to handle errors generated in calls the the main operations. You would need to handle that in your own code.
 - Could it be environmental?? Can you get the sample app to work in your environment?

Hopefully I can help more if you post some code.

**Comment by mike-goodwin** [comment] 2017-03-30 12:44
Hello,

I'm afraid I can't reproduce this - it works find in my sample app, my real app and my tests. If you are able to post some code I will be happy to look into it. In the meantime, a couple of thoughts:

Are you using the most up to date package (1.0.17)?
Are you sure the session info is being successfully written to the store?
Could it be that the session is expiring and being deleted in the background before you call destroy()? If so then the library will just call the callback you supply to session.destroy() reporting the error - it does not attempt to handle errors generated in calls the the main operations. You would need to handle that in your own code.
Could it be environmental?? Can you get the sample app to work in your environment?
Hopefully I can help more if you post some code.

**Comment by ailon** [comment] 2017-03-30 12:48
Thank you for the prompt reply @mike-goodwin-sage! Appreciated.

Answers to your questions/thoughts:

- yes, I'm using 1.0.17
- yes, session data is successfully written to the store and everything works perfectly if I don't call session.destroy()
- It's very unlikely that the session is expiring before I call destroy(). The issue happens with 100% certainty in my case after every call to destroy(). If I don't call destroy everything continues to work fine.
- I'll try to see if sample works in my environment and get back to you.

**Comment by mike-goodwin** [comment] 2017-04-21 19:36
Just following up on this. Were you able to find a solution? I'd be very happy to look into it further if you can post some code.

**Comment by mike-goodwin** [comment] 2017-05-23 11:50
Hello - did you ever get this working? I'd like to close the issue if it has been resolved...

**Comment by ailon** [comment] 2017-05-27 05:59
Hi Mike... sorry for not replying earlier! Unfortunately I wasn't able to find a solution to this in a reasonable timeframe and moved away from trying to use Azure Table Storage for sessions. There isn't much I have to contribute, unfortunately.

**Comment by mike-goodwin** [comment] 2017-07-20 16:59
Closing

**Closed by mike-goodwin** 2017-07-20 16:59 UTC
